### PR TITLE
resolved merge conflicts and fixed the mutliple inheritance

### PR DESCRIPTION
**Pull request by jovanbulck**
also checkout the mutliple "TODO jo: blabla" comments in `communicator.py`

### CODE REVIEW

**Comment by GijsTimmers** [comment]
Looks like we're doing work at the same time.

**Comment by jovanbulck** [comment]
idd ;-) 

wait 5 sec cause the merge conflicts are getting too big ;-)

**Comment by GijsTimmers** [comment]
OK. Some notes:

- I accidentally worked on the master branch instead of the dev branch. Please use the master branch for the time being
- I'll stay idle for a while now. Maybe you can merge your work into the `master` branch?
- When everything is done, I'll re-create the `dev` branch and pull from the master. We'll continue working there.
- As soon as we've got a working `kotnetcli`, we'll pull `dev` commits into the master.

**Comment by jovanbulck** [comment]
check :+1:

- should merge properly with master now :-)
- I'll stay idle too for a while, just wanted to merge these last changes
- go ahead pulling master into dev and maybe revert master to the last working version or so?

**Pull request merged**
